baseURL: "https://fish10101919.github.io/lab-website/"
title: "王昭雯實驗室 | NCKU"
theme: "PaperMod"
languageCode: "zh-tw"
menu:
  main:
    - name: "研究方向"
      url: "research"
      weight: 10
    - name: "實驗室成員"
      url: "members"
      weight: 20
    - name: "學術論文"
      url: "publications"
      weight: 30
    - name: "生活剪影"
      url: "gallery"
      weight: 40
    - name: "誠徵人才"
      url: "openings"
      weight: 50
